# Generated by Django 2.2.8 on 2020-03-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('technologies', models.CharField(max_length=100)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('display_pic', models.FileField(upload_to='')),
            ],
        ),
    ]
