# Generated by Django 2.2.8 on 2020-03-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0003_delete_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Marks', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
