# Generated by Django 2.2.8 on 2020-03-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0004_userform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='Last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
