# Generated by Django 2.2.8 on 2020-03-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0005_auto_20200330_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('Last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
